name: unit-test

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      config: 'Release'

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '5.0.x'

      - name: Install dependencies
        run: dotnet restore source/

      - name: Build
        run: dotnet build source/ --configuration $config --no-restore
        
      - name: Test      
        run: dotnet test source/ --no-restore --no-build --configuration $config