name: unit-test-pr

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      config: 'Release'

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: '5.0.x'

      - name: Install dependencies
        run: dotnet restore source/

      - name: Build
        run: dotnet build source/ --configuration $config --no-restore
        
      - name: Set PR Build Number
        id: PRNUMBER
        uses: kkak10/pr-number-action@v1.3

      - name: Set Test Title
        run: | 
              echo "title=Test Run for PR #${{steps.PRNUMBER.outputs.pr}} (${{github.run_number}})" >> $GITHUB_ENV
              echo "file_name=TestReport.${{steps.PRNUMBER.outputs.pr}}.${{github.run_number}}.md" >> $GITHUB_ENV

      - name: Test PR      
        run: dotnet test source/ --no-restore --no-build --configuration $config --logger:"liquid.md;LogFileName=${{github.workspace}}/${{env.file_name}};Title=${{env.title}};"

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: 'Test Run'
          path: ${{github.workspace}}/${{env.file_name}}

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: ${{env.file_name}}
